import { Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import {NextUIProvider} from "@nextui-org/react";
import Provider from "@/components/provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
      <NextUIProvider>
        <Navbar/>
        <Theme>
        {children}
        </Theme>
        </NextUIProvider>
        </Provider>
      </body>
    </html>
  );
}
